{% set version = "0.10.0" %}

package:
  name: stdlib-list
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stdlib_list/stdlib_list-{{ version }}.tar.gz
  sha256: 6519c50d645513ed287657bfe856d527f277331540691ddeaf77b25459964a14

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip

  run:
    - python

test:
  imports:
    - stdlib_list
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/stdlib-list/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A list of standard libraries for Python 2.6 through 3.12.
  description: |
    This package includes lists of all of the standard libraries for Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, and 3.12,
    along with the code for scraping the official Python docs to get said lists.
  dev_url: https://github.com/pypi/stdlib-list/
  doc_url: https://pypi.github.io/stdlib-list/

extra:
  recipe-maintainers:
    - woodruffw
