{% set name = "stdlib-list" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace("-", "_") }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 517824f27ee89e591d8ae7c1dd9ff34f672eae50ee886ea31bb8816d77535675

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - stdlib_list
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://pypi.org/project/stdlib-list/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A list of standard libraries for Python 2.6 through 3.12.
  description: |
    This package includes lists of all of the standard libraries for Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, and 3.12,
    along with the code for scraping the official Python docs to get said lists.
  dev_url: https://github.com/pypi/stdlib-list/
  doc_url: https://pypi.github.io/stdlib-list/

extra:
  recipe-maintainers:
    - woodruffw
