{% set version = "0.10.0" %}

package:
  name: stdlib-list
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stdlib_list/stdlib_list-{{ version }}.tar.gz
  sha256: 6519c50d645513ed287657bfe856d527f277331540691ddeaf77b25459964a14

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<37]

requirements:
  build:
    - python
    - flit-core >=3.2,<4
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - stdlib_list
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/jackmaney/python-stdlib-list
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A list of Python Standard Libraries (2.6-7, 3.2-9)
  description: |
    This package includes lists of all of the standard libraries for Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, and 3.9
    along with the code for scraping the official Python docs to get said lists.
  dev_url: http://github.com/jackmaney/python-stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
