travis:
  secure:
    BINSTAR_TOKEN: CJVr7Luuw9NcREALJNI2AEgKK8pXHwUOzwK7Dqh9BNQPLlrEjc8jZ3GW9UdsqF1UosixjMZFFQBT+7JhPJPRdlWGXhlrSjgGb33La7RcIGiH/MXVnigHeCgMMVj70bfhQ7NNu4ZdfxLDTZSFe5vjbIXkB3b66FKhdoOAvJbsVJd6dwgmOC2XuvjQekumNDdJHJRauMn7jQ74DZOwL+UutqksTZx6Ckahhe9GsP4Pu+xlBXZcsRRzS8qvKGhChKJHtZZND2n0YBPJHp1uDwZ9j7Fpfc7PyieSGicYcNF9DkJOvkwyp3bMbR803eg27meNkthWG2pMjzmWeX63kJ2h+vqgkRSTOZlBnXzHPhrZ8bg0KrAdLEZadCgvSCcK8xLNLi/UdDN1vah6e6xwqA7ICCboyFYffBFMPpkw6CafxNPTNEV0iZVnWon9MZ9lWIMVzcXuc4j2PgGqg9rWGZBQLv91kewYCT5WAiCDeQzrSxABDvlbs6v9ZfnvqtSGIMZ1q2dDhe1sMO0VV7BwPs3v3vBy/TV3/iBJo39Fl+IGjC1llmMcQFfxJuTWc8Pzjc8MVy0IE6lrfISOQJD6opezj2GhbZOGTef3OjTqpfGxTdwv5c5j5eZ/1R+JtHyyJG2oPG09L7sgknQKMuVEiT6Wst/4IUeYi0w3Or+xK340YoE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
