travis:
  secure:
    BINSTAR_TOKEN: A0Jjqsx53Pbr8mXDk47zHP25Z1ORdGiW88c1B/D162Y66808yH6WJfgDABnFu83asb3QcoUaBWSXPtk1Z4udNzNkxHXGNq+pK7iKOxmyhmN1OVE+T21OBfUlBeUDIUSGuk48kNTWi8DGSoH6XajOK0W8aQJGI+Tjd1xU7JxPfWE+y7e45S4UDuB+jjH+LZjqqLUwxFhYCdTFiSulwF/E2SLgtmMdNlnq3fcRro5QGq5o6xDgAXODKxReqRecKg/C2eS46uQBNxddSl0fFP01cOx9VWRjXJkrK6RPRZsAYiSwgqojO6q6hBoXy0/9OKUk4rv9G3p7R2IPMuWklA8MxkwhIyEiIVqH4+GMy0VdWeGx65FbEfjNvAgGGyGDK/FmF9EVaCZtSBu7LU3xIaH/wxFV4e1z2DpQsgCe+O0dgaC9ZIm3Y/qYzRameAApYWlQ9vuJEIgORDnKv6KGQm3g458lFbwi9BdaFjqVe9kTnVFuH8U1MU/Ztmk75l1NIX6FMmxomkTX8KMYNill0nObrHF4h8UFFjSnSjpQMk2h200+aA8FLm87j0IOgIp6frsxcLw9eaRqfd9fqdRMluZsDHXBxkzjFg1DXaQV9oLYFPxsMHvSZNeKD5s1i5bnGIrrmrGIcDjKg28b3MxVC+FmrVbMi5ISFki+De4XLYURINY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
